#!/usr/bin/env python3
"""Checks that the committed documentation screenshots and the pages that use
them agree with each other.

Run by `make ci`.

Two directions, and only one of them is covered by anything else. A *missing*
file is a broken image, which `zensical build --strict` already fails on. An
*unreferenced* file is silent: 200 KiB of committed PNG that no page shows,
left behind when a page was rewritten or a capture renamed. Since these are
regenerated by scripts/gen_screenshots.sh and committed, that dead weight lands
in the history permanently.

Deliberately dumb, like the other checks here: a regex for the path is the set
the pages ask for, and the directory listing is the set that exists.
"""

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SHOTS = REPO / "docs" / "assets" / "screenshots"
REFERENCE = re.compile(r"assets/screenshots/([\w.-]+\.png)")


def main():
    if not SHOTS.is_dir():
        print("check_screenshots: no screenshots directory — nothing to check")
        return

    referenced = set()
    for page in (REPO / "docs").rglob("*.md"):
        referenced |= {m.group(1) for m in REFERENCE.finditer(page.read_text())}

    present = {p.name for p in SHOTS.glob("*.png")}

    problems = []
    for name in sorted(present - referenced):
        problems.append(f"{name} is committed but no page shows it")
    for name in sorted(referenced - present):
        problems.append(f"{name} is referenced by a page but does not exist")

    if problems:
        print("check_screenshots: found problems:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print("\nRegenerate with `make screenshots`, or fix the reference.", file=sys.stderr)
        sys.exit(1)

    print(f"screenshots checked: {len(present)} committed, all shown by a page")


if __name__ == "__main__":
    main()
