#!/usr/bin/env python3
"""Builds the metric-adjusted fallback faces for the UI font, writing them into
web/css/base.css between the generated-region markers. Run manually when the UI
face, the fallback list or the locale copy changes; output is committed, this
script is not part of the build.

    python3 scripts/gen_font_fallbacks.py

WHY THIS EXISTS. base.css asks for Inter with font-display: swap, so the
platform font still paints the first frame of a cold load. Stage 41 Milestone 2
measured what that costs: on a 324px viewport, 77 to 94 percent of the elements
on a route moved when Inter arrived, some of them by 68px, and page heights
changed by up to 68px. A reader watched the whole page rearrange itself.

A fallback face cannot change which font the platform has. What it can do is
state how that font should be *fitted* to the box Inter will occupy:
size-adjust scales the glyphs, and ascent/descent/line-gap-override replace the
line box. Get both right and the first frame lands where the second one will.

WHY THE LOCALE FILES. size-adjust is the ratio of average character width
between the two fonts, and "average" depends entirely on which characters you
average. The usual recipe -- a flat pass over A-Z, a-z and the digits -- gives
97.57% for DejaVu Sans. Weighting each character by how often it actually
occurs in web/locales/*.json gives 94.03%. The browser, measured directly,
says 93.91%. Real interface copy is mostly lowercase and spaces, and that is
exactly where Inter is proportionally narrowest; the flat average is dominated
by capitals nobody types. So the corpus is the app's own copy, both locales.

WHY ONLY THESE FONTS. Every face below was measured from a font file on the
machine that ran this script. Segoe UI and the Apple system font are the
obvious omissions -- they are what system-ui resolves to on Windows and macOS,
they are almost certainly the two most common fallbacks in practice, and
neither can be measured here. Published metrics for them exist, but a number
nobody in this repository can check is exactly the kind of thing Stage 14 and
Stage 40 both got burned by, so they are left out and readers on those
platforms keep the unadjusted behaviour. Adding them is a measurement on a
Windows or macOS machine away, not a guess.

Note also what is deliberately NOT here: Arial. It is metric-compatible with
Liberation Sans, so it could be adjusted accurately -- but it sits in front of
system-ui in the cascade, so listing it would take Windows readers off Segoe UI
and onto Arial for the sake of a frame. A worse font that lands in the right
place is not obviously a trade worth making, and it is not ours to make
silently.

Requires fonttools (`pip install fonttools`). Fonts come from the distribution
packages named below; --source-root adds a second place to look for them,
which is what lets this run against a tree extracted with rpm2cpio on a machine
where installing them would need root.
"""

import argparse
import collections
import glob
import json
import os
import sys

from fontTools.ttLib import TTFont

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))

TARGET = ("Inter", "web/fonts/inter-400.woff2")

# (family as CSS local() must name it, package, glob for the regular face).
# Ordered by how likely the reader is to actually have it as their system-ui,
# because the cascade takes the first one that resolves.
FALLBACKS = [
    ("Roboto", "google-roboto-fonts", "/usr/share/fonts/google-roboto/Roboto-Regular.ttf"),
    ("DejaVu Sans", "dejavu-sans-fonts", "/usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf"),
    ("Noto Sans", "google-noto-sans-fonts", "/usr/share/fonts/google-noto*/NotoSans[-_]*Regular*"),
    ("Cantarell", "abattis-cantarell-fonts", "/usr/share/fonts/abattis-cantarell-fonts/Cantarell-Regular*"),
    ("Adwaita Sans", "adwaita-sans-fonts", "/usr/share/fonts/adwaita-sans-fonts/AdwaitaSans-Regular*"),
    ("Liberation Sans", "liberation-sans-fonts", "/usr/share/fonts/liberation-sans-fonts/LiberationSans-Regular.ttf"),
    ("Open Sans", "open-sans-fonts", "/usr/share/fonts/open-sans/OpenSans*Regular*"),
]

CSS_FILE = os.path.join(ROOT, "web", "css", "base.css")
BEGIN = "/* BEGIN generated by scripts/gen_font_fallbacks.py -- do not edit by hand */"
END = "/* END generated by scripts/gen_font_fallbacks.py */"


def load(path):
    """The metrics a browser derives a line box from, normalised to the em."""
    font = TTFont(path, fontNumber=0)
    os2, hhea, upem = font["OS/2"], font["hhea"], font["head"].unitsPerEm
    # Bit 7 of fsSelection is USE_TYPO_METRICS: when it is set the typo values
    # are authoritative, and when it is not, browsers use hhea. Reading the
    # wrong pair is a silent few-percent error in the line box.
    if os2.fsSelection & (1 << 7):
        asc, desc, gap = os2.sTypoAscender, -os2.sTypoDescender, os2.sTypoLineGap
    else:
        asc, desc, gap = hhea.ascent, -hhea.descent, hhea.lineGap
    return {
        "cmap": font.getBestCmap(),
        "hmtx": font["hmtx"],
        "upem": upem,
        "ascent": asc / upem,
        "descent": desc / upem,
        "gap": gap / upem,
    }


def advance(face, char):
    glyph = face["cmap"].get(ord(char))
    return None if glyph is None else face["hmtx"][glyph][0] / face["upem"]


def corpus():
    """Character frequencies over every shipped locale."""
    counts = collections.Counter()

    def walk(node):
        if isinstance(node, str):
            counts.update(node)
        elif isinstance(node, dict):
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    paths = sorted(glob.glob(os.path.join(ROOT, "web", "locales", "*.json")))
    if not paths:
        sys.exit("no locale files under web/locales - nothing to weight the average by")
    for path in paths:
        with open(path, encoding="utf-8") as handle:
            walk(json.load(handle))
    # The braces are the interpolation syntax, not text anybody reads.
    for brace in "{}":
        counts.pop(brace, None)
    return counts, [os.path.basename(p) for p in paths]


def resolve(pattern, source_root):
    """The installed font, or the same path under an extracted package tree.

    --source-root is an additional place to look rather than a replacement, so
    a machine that has most of these installed and one extracted only has to
    extract the one.
    """
    for candidate in ([source_root + pattern] if source_root else []) + [pattern]:
        matches = sorted(glob.glob(candidate))
        if matches:
            return matches[0]
    return None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-root",
        default="",
        help="extra search prefix for font paths, for a package tree extracted with rpm2cpio",
    )
    args = parser.parse_args()

    target = load(os.path.join(ROOT, TARGET[1]))
    counts, locale_files = corpus()
    print(f"corpus: {sum(counts.values())} characters from {', '.join(locale_files)}")

    rules = []
    families = []
    for family, package, pattern in FALLBACKS:
        path = resolve(pattern, args.source_root)
        if path is None:
            sys.exit(
                f"missing {args.source_root + pattern} - is {package} installed?\n"
                "Every face in FALLBACKS must be measurable, or the committed CSS would\n"
                "depend on which fonts the machine that last ran this happened to have."
            )
        face = load(path)
        shared = {c: n for c, n in counts.items()
                  if advance(target, c) is not None and advance(face, c) is not None}
        total = sum(shared.values())
        target_avg = sum(advance(target, c) * n for c, n in shared.items()) / total
        face_avg = sum(advance(face, c) * n for c, n in shared.items()) / total
        size_adjust = target_avg / face_avg
        # The overrides are expressed against the *adjusted* em, so each one is
        # divided by the same factor the glyphs were scaled by.
        name = f"{TARGET[0]} fallback {family}"
        families.append(f'"{name}"')
        rules.append(
            f'/* {family}: from {os.path.basename(path)} ({package}) */\n'
            f"@font-face {{\n"
            f'  font-family: "{name}";\n'
            f'  src: local("{family}");\n'
            f"  size-adjust: {size_adjust * 100:.2f}%;\n"
            f"  ascent-override: {target['ascent'] / size_adjust * 100:.2f}%;\n"
            f"  descent-override: {target['descent'] / size_adjust * 100:.2f}%;\n"
            f"  line-gap-override: {target['gap'] / size_adjust * 100:.2f}%;\n"
            f"}}"
        )
        print(f"  {family:<17} size-adjust {size_adjust * 100:6.2f}%   [{os.path.basename(path)}]")

    block = "\n\n".join(rules)
    stack = ",\n    ".join(families)
    generated = (
        f"{BEGIN}\n"
        f"{block}\n\n"
        f"/* The list the UI stack interpolates, in cascade order. */\n"
        f":root {{\n"
        f"  --font-ui-fallback:\n    {stack};\n"
        f"}}\n"
        f"{END}"
    )

    with open(CSS_FILE, encoding="utf-8") as handle:
        css = handle.read()
    start, stop = css.find(BEGIN), css.find(END)
    if start < 0 or stop < 0:
        sys.exit(f"markers not found in {CSS_FILE} - add {BEGIN} / {END} first")
    css = css[:start] + generated + css[stop + len(END):]
    with open(CSS_FILE, "w", encoding="utf-8") as handle:
        handle.write(css)
    print(f"wrote {len(rules)} faces into {os.path.relpath(CSS_FILE, ROOT)}")


if __name__ == "__main__":
    main()
